{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.5.0.jar",
          "url": "builder-8.5.0.jar",
          "size": 14095727,
          "sha512": "270713791eb3713c6da5414011b553b5687b5c4c2a60837884c9a77a54b4900335fedd2e1d5fed5fa824c8b6740af29f33e025453e6eda2a0072dc14ff4c5aa5",
          "sha256": "06ca45826dd49604dc05b5986dea2e59977b01cfba3fd476e6728f906e76facf",
          "sha1": "b67b3f37071bee0d38a4b1e7ce5b9da9ba9ca139",
          "md5": "0477d8ce6e0a23ab710a7fd47cdfdf77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.5.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.5.0.jar",
          "url": "builder-8.5.0.jar",
          "size": 14095727,
          "sha512": "270713791eb3713c6da5414011b553b5687b5c4c2a60837884c9a77a54b4900335fedd2e1d5fed5fa824c8b6740af29f33e025453e6eda2a0072dc14ff4c5aa5",
          "sha256": "06ca45826dd49604dc05b5986dea2e59977b01cfba3fd476e6728f906e76facf",
          "sha1": "b67b3f37071bee0d38a4b1e7ce5b9da9ba9ca139",
          "md5": "0477d8ce6e0a23ab710a7fd47cdfdf77"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.5.0-javadoc.jar",
          "url": "builder-8.5.0-javadoc.jar",
          "size": 397693,
          "sha512": "bd14dd3bbe9ee5609127915d2bbfb439810a8186ff8b1e6ad0641ea85c14491a7823845fc130a6027e23b6399b7c6ab0fc99b665a4d17a2456cb53bfb371df19",
          "sha256": "07359b52828f414ca26b3cc06c0dd59ebf8e990a15c3f95019e3ef74c0709a1d",
          "sha1": "eb942b679f5d56486fe8d83166db529dd31817df",
          "md5": "b8966663a675e5ff89fac240031aa16a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.5.0-sources.jar",
          "url": "builder-8.5.0-sources.jar",
          "size": 280859,
          "sha512": "02b8153bd8037bb8a00eea99094abcb2400a74eaca8e9e2301544264f7923b2c46f56b2e8ee88ce17adb773dc76d4b60c37f790a6773f9539f5858308cc7788b",
          "sha256": "a0e5bafc010509042a8bfd336c0b1566aa90e3b67a3f0af56f6766c74d480719",
          "sha1": "3d7c88b19f0892c5db3f8968fca0e8a69787497f",
          "md5": "9ed6f81a3eda6723e1708f7b1d30a447"
        }
      ]
    }
  ]
}
